import { create } from "zustand";
import { devtools } from "zustand/middleware";

type instaUserStoreType = {
  currentVid: number;
  vidMeta: { name: string; description: string; compte: string; hashtag: string }[];
};

export const vidNb = 10;
export const startVid = Math.floor(Math.random() * vidNb);

export const initInstaUserStore = {
  currentVid: startVid,
  vidMeta: [],
};

export const useInstaUserStore = create(devtools<instaUserStoreType>(() => ({ ...initInstaUserStore })));

export const setInstaCurrentVid = (currentVid: number) => {
  useInstaUserStore.setState({ currentVid });
};

export const setInstaVidMeta = () => {
  useInstaUserStore.setState({ vidMeta: genererVideosAnimalieres() });
};

function genererVideosAnimalieres() {
  const nomsAnimaux = [
    "Sieste d'un petit rêveur",
    "Découvertes au jardin",
    "L'heure du bain",
    "Festival de bâillements",
    "Secrets d'un gourmand",
    "Amitié sans limites",
    "Concert de ronrons",
    "Journée ensoleillée",
    "Séance de jeu",
    "Câlins à gogo",
    "Explorateur en herbe",
    "Premiers pas magiques",
    "Rencontre inattendue",
    "Curiosité en action",
    "Bêtises adorables",
    "Sauts et pirouettes",
    "Sieste parfaite",
    "Regard attendrissant",
    "Joies de la neige",
    "Ange malicieux",
    "Roi de la cachette",
    "Complicité unique",
    "Acrobate en herbe",
    "Grimaces hilarantes",
    "Gourmandise intense",
    "Secrets d'un dormeur",
    "Câlins et bisous",
    "Musique douce",
    "Balade en forêt",
    "Artiste en herbe",
    "Danse de la joie",
    "Miaulements joyeux",
    "Petit chasseur",
    "Tendresse absolue",
    "Amitié forte",
    "Journée à la plage",
    "Clown surprise",
    "Bulles de savon",
    "Ronflements doux",
    "Petit nageur",
    "Curiosité récompensée",
    "Journée à la campagne",
    "Explorateur extrême",
    "Danse de la pluie",
    "Pépiements joyeux",
    "Petit grimpeur",
    "Tendresse infinie",
    "Amour sans limites",
    "Jeux d'eau",
    "Découverte de la nature",
    "Jeux avec des jouets",
    "Réactions amusantes",
    "Moment de détente",
    "Jeux avec des balles",
    "Réactions à la musique",
    "Jeux avec des plumes",
    "Rencontres avec d'autres animaux",
  ];

  const descriptions = [
    "Un moment de pure douceur.",
    "L'aventure commence ici.",
    "Des éclaboussures et du rire.",
    "Un spectacle de somnolence.",
    "Irrésistiblement mignon.",
    "Une amitié touchante.",
    "Mélodie de ronrons.",
    "La joie à l'état pur.",
    "Énergie débordante.",
    "Tendresse infinie.",
    "Exploration et découverte.",
    "Un moment magique.",
    "Surprise et émerveillement.",
    "Curiosité sans limite.",
    "Bêtises et rires.",
    "Agilité et grâce.",
    "Détente absolue.",
    "Un regard qui fait fondre.",
    "Joies de l'hiver.",
    "Malice et charme.",
    "Maître de la cachette.",
    "Complicité parfaite.",
    "Prouesses impressionnantes.",
    "Hilarité garantie.",
    "Gourmandise à son comble.",
    "Douce somnolence.",
    "Amour et tendresse.",
    "Apaisement musical.",
    "Nature et découverte.",
    "Créativité en action.",
    "Joie contagieuse.",
    "Mélodie de miaulements.",
    "Instinct de chasse.",
    "Tendresse infinie.",
    "Amitié inébranlable.",
    "Plaisirs de la plage.",
    "Surprises et rires.",
    "Magie des bulles.",
    "Douce mélodie de ronflements.",
    "Plaisirs aquatiques.",
    "Récompense de la curiosité.",
    "Joies de la campagne.",
    "Aventures extrêmes.",
    "Danse sous la pluie.",
    "Mélodie de pépiements.",
    "Agilité en hauteur.",
    "Tendresse éternelle.",
    "Amour inconditionnel.",
    "Rafraîchissement garanti.",
    "Nature et découverte.",
    "Plaisir ludique.",
    "Réactions hilarantes.",
    "Détente assurée.",
    "Plaisir rebondissant.",
    "Réactions surprenantes.",
    "Plaisir plumeux.",
    "Exploration sociale.",
    "Regardez ce petit trésor s'endormir paisiblement, bercé par ses rêves les plus doux. Une véritable bouffée de tendresse pour bien commencer la journée.",
    "Suivez ce petit explorateur dans sa découverte du jardin, où chaque feuille, chaque fleur est une nouvelle aventure. Préparez-vous à être émerveillés !",
    "L'heure du bain n'a jamais été aussi amusante ! Entre éclaboussures et grimaces, ce petit compagnon va vous faire fondre de rire.",
    "Un véritable concert de bâillements, chacun plus adorable que le précédent. Laissez-vous emporter par cette vague de douceur et de somnolence.",
    "Découvrez les secrets d'un petit gourmand qui ne résiste à aucune friandise. Ses réactions sont tout simplement irrésistibles !",
    "Quand l'amitié n'a pas de limites, ça donne des scènes incroyables de complicité et de tendresse. Préparez vos mouchoirs, l'émotion est au rendez-vous.",
    "Un moment musical improvisé avec des ronrons à gogo. Laissez-vous bercer par cette mélodie douce et réconfortante.",
    "Une journée ensoleillée remplie de joie et de découvertes. Ce petit compagnon va vous transmettre sa bonne humeur contagieuse.",
    "Une séance de jeu endiablée où l'énergie débordante de ce petit animal va vous impressionner. Préparez-vous à être émerveillés par ses prouesses !",
    "Les câlins, c'est la vie ! Et ce petit animal le prouve avec des scènes de tendresse à couper le souffle. Vous allez fondre !",
    "Suivez les aventures de ce petit explorateur dans son quotidien, où chaque jour est une nouvelle découverte. Vous allez adorer.",
    "Un moment de tendresse et de complicité entre amis, l'amitié à son plus haut niveau.",
    "Les bêtises les plus mignonnes que vous verrez aujourd'hui, impossible de ne pas craquer !",
    "Un festival de câlins et de ronronnements pour vous réchauffer le cœur, parfait pour l'hiver.",
    "Le quotidien d'un petit curieux qui découvre le monde qui l'entoure, une vraie leçon de vie.",
    "Un festival de sauts et de pirouettes, ce petit acrobate va vous impressionner par son agilité et sa grâce.",
    "L'art de la sieste parfaite, un moment de détente absolue où ce petit animal vous montre comment se relaxer en toute sérénité.",
    "Un regard qui fait fondre, des yeux remplis de douceur et de tendresse qui vont vous faire craquer instantanément.",
    "Les joies de la neige, des moments de jeu et de découverte dans un paysage enneigé, une véritable féerie hivernale.",
    "Un petit ange plein de malice, des bêtises adorables qui vont vous faire rire aux éclats et vous attendrir en même temps.",
  ];

  const nomsComptes = [
    "LesAnimauxTropMignons",
    "InstaVieAnimale",
    "LeMondeDesPetitesPattes",
    "CutenessOverdose",
    "DailyDoseOfHappiness",
    "BestAnimalBuddies",
    "TropChouCompany",
    "LesRoisDeLaMignonnerie",
    "AnimauxEnFolie",
    "LeMondeDesAnimauxAdorables",
    "LesAventuresDeBouleDePoils",
    "InstaAnimauxDeCompagnie",
    "LeCoinDesAnimauxMignons",
    "LaPlanèteDesAnimaux",
    "AnimauxDuMondeEntier",
    "LesAmisPoilusPourToujours",
    "MignonnerieGarantie",
    "AnimauxTropCraquants",
    "LaVieDesAnimaux",
    "AnimauxDeLaJoie",
    "LesPetitsCurieux",
    "InstaTendresseAnimale",
    "LeRoyaumeDesAnimaux",
    "AnimauxDuQuotidien",
    "LesExplorateursMignons",
    "InstaRireAnimalier",
    "AnimauxEnAction",
    "LesAmisDeLaNature",
    "AnimauxEtCompagnie",
    "InstaDouceurAnimale",
  ];

  const hashtags = [
    "#CâlinAnimal #DouxCompagnon",
    "#YeuxAttendrissants #MuseauCurieux #PetiteBouleDePoils",
    "#BébéAnimal #MomentsMignons #InstaAnimaux",
    "#AmourAnimal #CompagnonFidèle #TendresseInfinie",
    "#AnimauxRigolos #SourireAnimal",
    "#CâlinsGratuits #AmisPoilus #CoeurFondant",
    "#RiresAnimaux #BêtisesMignonnes",
    "#SiesteAnimal #RêvesDoux",
    "#ExplorationAnimal #CuriositéInnée #AventuresMignonnes",
    "#JeuxAnimaux #PlaisirPartagé",
    "#RegardAttendrissant #ExpressionMignonne",
    "#BébésAnimauxMignons #TendresseAbsolue",
    "#AnimauxCâlins #DouxRêves #NuitPaisible",
    "#PetitesPattes #GrandsCoeurs",
    "#MuseauxMignons #BisousAnimaux",
    "#AnimauxJoueurs #MomentsDeJoie",
    "#CâlinsPoilus #AmisPourLaVie",
    "#YeuxBrillants #ÂmeInnocente",
    "#AnimauxCurieux #ExplorationDuMonde",
    "#BébésAttendrissants #MomentsPrécieux",
    "#AnimauxDormeurs #RêvesPaisibles",
    "#PattesDouces #CâlinsRéconfortants",
    "#MuseauxAttendrissants #BisousPoilus",
    "#AnimauxRigolos #MomentsDePlaisir",
    "#CâlinsInfinis #AmisPoilusPourToujours",
    "#YeuxAdorables #ÂmePureEtSimple",
    "#AnimauxExplorateurs #DécouvertesQuotidiennes",
    "#BébésMignons #MomentsMagiques",
    "#AnimauxPaisibles #RêvesDouxEtPaisibles",
    "#PattesAttendrissantes #CâlinsChaleureux",
    "#MuseauxDoux #BisousTendres",
    "#AnimauxJoueursEtRigolos #MomentsDeFolie",
    "#CâlinsChaleureux #AmisPoilusPourLaVie",
    "#YeuxAttendrissantsEtBrillants #ÂmeInnocenteEtPure",
    "#AnimauxCurieuxEtExplorateurs #AventuresInoubliables",
    "#BébésAdorables #MomentsPrécieuxEtMagiques",
    "#AnimauxDormeursEtPaisibles #RêvesDouxEtCalmes",
    "#PattesDouxEtAttendrissantes #CâlinsRéconfortantsEtChaleureux",
    "#MuseauxAttendrissantsEtDoux #BisousTendresEtPoilus",
    "#AnimauxRigolosEtJoueurs #MomentsDePlaisirEtDeFolie",
    "#CâlinsInfinisEtChaleureux #AmisPoilusPourToujoursEtÀJamais",
    "#YeuxAdorablesEtBrillants #ÂmePureEtInnocente",
    "#AnimauxExplorateursEtCurieux #DécouvertesQuotidiennesEtInoubliables",
    "#BébésMignonsEtAdorables #MomentsMagiquesEtPrécieux",
    "#AnimauxPaisiblesEtDormeurs #RêvesDouxEtPaisibles",
    "#PattesAttendrissantesEtDouces #CâlinsChaleureuxEtRéconfortants",
    "#MuseauxDouxEtAttendrissants #BisousTendresEtPoilus",
    "#AnimauxJoueursEtRigolos #MomentsDePlaisirEtDeFolie",
    "#CâlinsInfinisEtChaleureux #AmisPoilusPourToujoursEtÀJamais",
    "#YeuxBrillantsEtAdorables #ÂmeInnocenteEtPure",
  ];

  const videosMeta = new Array(vidNb);

  for (let i = 0; i < vidNb; i++) {
    const vidMeta = {
      name: nomsAnimaux[i % nomsAnimaux.length],
      description: descriptions[i % descriptions.length],
      compte: nomsComptes[i % nomsComptes.length],
      hashtag: hashtags[i % hashtags.length],
    };
    videosMeta[i] = vidMeta;
  }

  return videosMeta;
}
